### ISSUE TITLE
[Request] Debian package copyright file support

### ISSUE THREAD

**Issue by stefandz** [jordansissel/fpm#1222] opened 2016-11-02 17:24 UTC
Low priority (as it's easy to add by hand, which is what I currently do) but would be neat to have a switch something like `--deb-copyright FILEPATH` to include a copyright file in a Debian package.

TIA!

**Comment by 0xaf1f** [comment] 2017-07-06 14:25
Looks like a duplicate of #1116.

**Comment by josegonzalez** [comment] 2017-09-29 22:23
Closing as duplicate of #1045 .

**Closed by josegonzalez** 2017-09-29 22:23 UTC
