### ISSUE TITLE
fpm --provides="foo (= 1.0)" doesn't preserve the specified version in the deb package

### ISSUE THREAD

**Issue by philschwartzsonos** [jordansissel/fpm#1788] opened 2021-05-18 22:40 UTC
Example:
$ fpm -t deb -s empty -n foo_pkg -v 1.0rc --provides="foo (= 1.0)" --provides="bar" --deb-no-default-config-files
Created package {:path=>"foo-pkg_1.0rc_amd64.deb"}

$ dpkg --info foo-pkg_1.0rc_amd64.deb | grep Provides
 Provides: foo, bar

The expected output is:
Provides: foo (= 1.0), bar

**Comment by tympanix** [comment] 2021-07-06 17:47
Same issue. From https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides
> A Provides field may contain version numbers, and such a version number will be considered when considering a dependency on or conflict with the virtual package name.

**Comment by jordansissel** [comment] 2021-07-06 18:48
Interesting. I looked at the cause, and this is intentional behavior by fpm, shown here: 

https://github.com/jordansissel/fpm/blob/dbd8bafb5d057af7808e29d1df2302c42d79eb0b/templates/deb.erb#L26-L28

Research for this issue is below in this comment. I'll think about ways to solve this shortly.

A git commit for this change (ee72521b30c07cc1a4d8a83f2b57f84636cb5a63) references #280, which reads:

From: https://github.com/jordansissel/fpm/issues/280#issuecomment-9775027
> The debian policy manual (http://www.debian.org/doc/debian-policy/ch-relationships.html) does not specify if a version can be given in the 'Provides' field.

From: https://github.com/jordansissel/fpm/issues/280#issuecomment-9814053
> "A Provides field may not contain version numbers, and the version number of the concrete package which provides a particular virtual package will not be considered when considering a dependency on or conflict with the virtual package name."

These comments were from 2012.

It seems like in 2014 someone filed a wishlist feature for Debian to add version support to the `Provides` field: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761219

This wishlist item referenced a new feature in `dpkg` 1.17.11 which added support for a versioned `Provides` field: https://launchpad.net/debian/+source/dpkg/1.17.11

> * Add versioned Provides support:
>    - Add a new dpkg --assert-versioned-provides command.>
>    - Packages can provide a specific version, “virtual (= 1.0)” which will
>      be honored, previously it would just be accepted when parsing.
>    - Non-versioned virtual packages will not satisfy versioned dependencies.
>    - Versioned virtual packages will satisfy non-versioned dependencies.

An interesting note in the above is "previously it would just be accepted when parsing" -- I wonder if older versions of dpkg will just silently ignore versions in provides?

**Comment by jordansissel** [comment] 2021-07-06 19:02
Thinking about options:
1. Allow versioned `Provides` in deb packages with the risk that older deb platforms
2. or, Add a flag that toggles fpm's Provides version removal behavior.

Lets estimate risk of impacting older debian platforms. I don't have any older debian software available to me at this time, so research is the next best step to testing:

* dpkg 1.17.11 adds versioend Provides (Release: 2014)
* Debian: The oldest listed release is "jessie" which is also named "oldoldstable" and "Debian 8" (This naming scheme Debian uses is very confusing)
* [Debian package search](https://packages.debian.org/search?suite=jessie&exact=1&searchon=names&keywords=dpkg) shows Jessie has dpkg version 1.17.27.
* This version of dpkg was released in [March of 2016](https://launchpad.net/debian/+source/dpkg/1.17.27). 
* Debian Jessie aka [Debian 8 was released](https://www.debian.org/releases/jessie/) in April of 2015 with the latest update released in June of 2018.
* Ubuntu: The oldest listed release is "bionic" which is also named "18.04 LTS"
* [Ubuntu package search](https://packages.ubuntu.com/search?keywords=dpkg&searchon=names&exact=1&suite=all&section=all) shows Bionic has dpkg 1.19.0.5

I'd like to test if Debian/Ubuntu versions with older dpkg versions (older than dpkg v1.17.11) will work as expected before proceeding.

**Comment by jordansissel** [comment] 2021-07-06 19:16
If I attempt to leave `Provides` unmodified, things seem to work in Ubuntu 14.04 (dpkg v1.17.5), at least, somewhat as expected.

```
% git diff -U0
diff --git a/templates/deb.erb b/templates/deb.erb
index b24252c..543dfa0 100644
--- a/templates/deb.erb
+++ b/templates/deb.erb
@@ -28 +28 @@ Build-Depends: <%= attributes[:deb_build_depends].collect { |d| fix_dependency(d
-Provides: <%= provides.map {|p| p.split(" ").first}.join ", " %>
+Provides: <%= provides.join ", " %>
```

Testing, create two packages.
```
% fpm -f -t deb -s empty -n bar -v 1.0 --depends "foo (=1.0)" --deb-no-default-config-files
% fpm -f -t deb -s empty -n foo_pkg -v 1.0rc --provides="foo (= 1.0)" --provides="bar" --deb-no-default-config-files
```

Try them on Ubuntu 14.04 (which has a too-old version of dpkg):

```
% docker run -it $(ls {foo,bar}*.deb | xargs -I@ -- echo -v $PWD/@:/@:ro) ubuntu:14.04          
root@936c36425239:/# ls *deb
bar_1.0_amd64.deb  foo-pkg_1.0rc_amd64.deb

root@936c36425239:/# dpkg --info foo-pkg_1.0rc_amd64.deb  |grep Provides
 Provides: foo (= 1.0), bar

root@936c36425239:/# dpkg --info bar_1.0_amd64.deb | grep Depends
 Depends: foo (=1.0)
```

Now, checking if we can install the foo-pkg:

```
root@936c36425239:/# dpkg -i foo-pkg_1.0rc_amd64.deb 
Selecting previously unselected package foo-pkg.
(Reading database ... 12097 files and directories currently installed.)
Preparing to unpack foo-pkg_1.0rc_amd64.deb ...
Unpacking foo-pkg (1.0rc) ...
Setting up foo-pkg (1.0rc) ...
```

:heavy_check_mark: Nice, no complaints from dpkg.

Next, trying to install `bar` which _should_ fail on this older version of `dpkg` because it doesn't support versioned `Provides`

```
root@936c36425239:/# dpkg -i bar_1.0_amd64.deb 
...
dpkg: dependency problems prevent configuration of bar:
 bar depends on foo (= 1.0); however:
  Package foo is not installed.
...
```

:warning: Expected this failure, so this isn't necessarily a problem.

**Comment by jordansissel** [comment] 2021-07-06 19:17
Trying the same test on Ubuntu 18.04 which _should_ a newer version of dpkg:

```
% docker run -it $(ls {foo,bar}*.deb | xargs -I@ -- echo -v $PWD/@:/@:ro) ubuntu:18.04

root@2a59607776f4:/# dpkg --version
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
...

root@2a59607776f4:/# dpkg -i foo-pkg_1.0rc_amd64.deb 
Selecting previously unselected package foo-pkg.
(Reading database ... 4051 files and directories currently installed.)
Preparing to unpack foo-pkg_1.0rc_amd64.deb ...
Unpacking foo-pkg (1.0rc) ...
Setting up foo-pkg (1.0rc) ...
root@2a59607776f4:/# dpkg -i bar_1.0_amd64.deb 
Selecting previously unselected package bar.
(Reading database ... 4053 files and directories currently installed.)
Preparing to unpack bar_1.0_amd64.deb ...
Unpacking bar (1.0) ...
Setting up bar (1.0) ...
```

:heavy_check_mark: Ok this works.

**Comment by philschwartzsonos** [comment] 2021-07-06 20:13
Thanks for looking into this Jordan!  For the one package that had this issue we ended up working around it by doing some fpm -> deb-dpkg surgery but would be nice to simplify the packaging with just fpm.

**Comment by jordansissel** [comment] 2021-07-06 20:17
@philschwartzsonos Working on a patch now. My original fix uncovered a bug in gem->deb conversions, so I'm fixing that along with this issue :)

**Comment by jordansissel** [comment] 2021-07-06 21:04
Another note. It looks like the policy change to allow `Provides` version values was implemented in debian-policy 4.4.0. Based on some searching, it seems like even Debian buster/stable has not received this update.

References:
* "Fixed in version debian-policy/4.4.0.0" - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761219
* Buster/stable has debian-policy 4.3.0.3. Bullseye/testing has 4.5.1.0, Sid/unstable has 4.5.1.0 - https://packages.debian.org/search?keywords=debian-policy&searchon=names&exact=1&suite=all&section=all

**Comment by philschwartzsonos** [comment] 2021-07-06 21:24
I can see the patch on the branch.  Thanks for that.  Are there any plans to release a new version of FPM or should I just use the branched version?

**Comment by jordansissel** [comment] 2021-07-06 21:25
@philschwartzsonos assuming nothing explodes, I should have a new version released in a few minutes ;)

**Closed** 2021-07-06 21:25 UTC

**Comment by philschwartzsonos** [comment] 2021-07-06 21:29
Great, thanks again!  Hoping that the bomb squad doesn't need to be deployed to your neighborhood.

**Comment by jordansissel** [comment] 2021-07-06 21:36
Haha. Sometimes the test suite goes sideways, but not today!

fpm 1.13.1 released with this fix -- https://fpm.readthedocs.io/en/latest/changelog.html#july-6-2021

```
% fpm -s empty -t deb --provides "foo (=1.2.3)" -n example
% dpkg --info example_1.0_amd64.deb | grep Provides:
 Provides: foo (=1.2.3)
```

**Comment by philschwartzsonos** [comment] 2021-07-06 21:41
Awesome, thanks!
